services:
  app:  
    image: ghcr.io/lukasarnoldla/myapp:latest
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 1
    command: python app.py
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: dhbwvsghcn
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db_data:
