services:
  app:  
    image: ghcr.io/praciqx/weatherstation-image:latest
    ports:
      - 5000:5000
    restart: on-failure
    environment:
      FLASK_DEBUG: 1
    command: python app.py
    cpus: 2
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: dhbwvsghcn
    volumes:
      - ./database:/var/lib/postgresql/data
    cpus: 2
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "dhbwvsghcn"]
      interval: 30s
      timeout: 10s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080
    cpus: 2
    mem_limit: 1g
